### ISSUE TITLE
Custom Google Maps in the Info page

### ISSUE THREAD

**Issue by andreaforni** [andreareginato/conference_site#13]
Hi guys,
I have written a custom Google Maps for the Info page. I used the Google Maps API and I changed the default pin with a "ruby" and its shadow (I used the same icon of the favicon):

![Custom Ruby Pin](https://github.com/andreaforni/conference_site/wiki/images/issues/custom_gmap/custom_ruby_pin.jpg)

If you click on the ruby, a info window appears with the information about the place conference:

![Custom Info Window](https://github.com/andreaforni/conference_site/wiki/images/issues/custom_gmap/custom_info_window.jpg)

I do not think is very useful to do a pull request now because we still don't know the place of the conference. All the changes are on my github repository, in the branch called "gmap_update".

bye,
Andrea

**Comment by andreaforni** [comment]
Ah, another issue: I used an API key associated with my personal Google account. Do we have a "official" Google Account for the RubyDayIT? If not, we can create it or we can continue to use my key.

**Comment by mcollina** [comment]
Make a pull request, we will update it when we know the exact location.

If it's not a problem for you, we will use your key :).

**Comment by andreaforni** [comment]
Ok, this evening I'll do the pull request.

We can use my key, for me there is no problem :-)
